#!/bin/sh

set -eu

usage()
{
	cat << EOF

Usage: lsinitramfs [-l] initramfs-file...

Options:
  -l   Display long and more verbose listing of initramfs content

See lsinitramfs(8) for further details.

EOF
}

if [ "$#" -eq 0 ] ; then
	usage >&2
	exit 2
fi

umi_opts="--list"

OPTIONS=$(getopt -o hl --long help,long -n "$0" -- "$@")
# Check for non-GNU getopt
# shellcheck disable=SC2181
if [ $? != 0 ] ; then echo "W: non-GNU getopt" >&2 ; exit 2 ; fi

eval set -- "$OPTIONS"

while true; do
        case "$1" in
        -h|--help)
		usage
		exit 0
	;;
	-l|--long)
		umi_opts="${umi_opts:+${umi_opts} --verbose}"
		shift
	;;
	--)
		shift
		break
	;;
	*)
		echo "Internal error!" >&2
		exit 1
	esac
done

for initramfs in "$@" ; do
	unmkinitramfs $umi_opts -- "$initramfs"
done
